# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcwin.ui'
#
# Created: Sat Apr 13 17:00:31 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Calc_Window(object):
    def setupUi(self, Calc_Window):
        Calc_Window.setObjectName(_fromUtf8("Calc_Window"))
        Calc_Window.resize(403, 581)
        Calc_Window.setMinimumSize(QtCore.QSize(403, 581))
        self.centralwidget = QtGui.QWidget(Calc_Window)
        self.centralwidget.setMinimumSize(QtCore.QSize(403, 581))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.search_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_lab.sizePolicy().hasHeightForWidth())
        self.search_lab.setSizePolicy(sizePolicy)
        self.search_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.search_lab.setMaximumSize(QtCore.QSize(100, 25))
        self.search_lab.setObjectName(_fromUtf8("search_lab"))
        self.horizontalLayout.addWidget(self.search_lab)
        self.search_line = QtGui.QLineEdit(self.centralwidget)
        self.search_line.setMinimumSize(QtCore.QSize(100, 25))
        self.search_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.search_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_line.setObjectName(_fromUtf8("search_line"))
        self.horizontalLayout.addWidget(self.search_line)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mass_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mass_lab.sizePolicy().hasHeightForWidth())
        self.mass_lab.setSizePolicy(sizePolicy)
        self.mass_lab.setMinimumSize(QtCore.QSize(70, 25))
        self.mass_lab.setMaximumSize(QtCore.QSize(70, 25))
        self.mass_lab.setObjectName(_fromUtf8("mass_lab"))
        self.horizontalLayout_2.addWidget(self.mass_lab)
        self.mass_line = QtGui.QLineEdit(self.centralwidget)
        self.mass_line.setMinimumSize(QtCore.QSize(100, 25))
        self.mass_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.mass_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mass_line.setObjectName(_fromUtf8("mass_line"))
        self.horizontalLayout_2.addWidget(self.mass_line)
        self.substitutebut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.substitutebut.sizePolicy().hasHeightForWidth())
        self.substitutebut.setSizePolicy(sizePolicy)
        self.substitutebut.setMinimumSize(QtCore.QSize(100, 25))
        self.substitutebut.setMaximumSize(QtCore.QSize(100, 25))
        self.substitutebut.setDefault(True)
        self.substitutebut.setObjectName(_fromUtf8("substitutebut"))
        self.horizontalLayout_2.addWidget(self.substitutebut)
        self.searchbut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchbut.sizePolicy().hasHeightForWidth())
        self.searchbut.setSizePolicy(sizePolicy)
        self.searchbut.setMinimumSize(QtCore.QSize(100, 25))
        self.searchbut.setMaximumSize(QtCore.QSize(100, 25))
        self.searchbut.setDefault(True)
        self.searchbut.setObjectName(_fromUtf8("searchbut"))
        self.horizontalLayout_2.addWidget(self.searchbut)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.prot_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prot_lab.sizePolicy().hasHeightForWidth())
        self.prot_lab.setSizePolicy(sizePolicy)
        self.prot_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.prot_lab.setMaximumSize(QtCore.QSize(100, 25))
        self.prot_lab.setObjectName(_fromUtf8("prot_lab"))
        self.horizontalLayout_3.addWidget(self.prot_lab)
        self.prot_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prot_sec_lab.sizePolicy().hasHeightForWidth())
        self.prot_sec_lab.setSizePolicy(sizePolicy)
        self.prot_sec_lab.setMinimumSize(QtCore.QSize(0, 25))
        self.prot_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.prot_sec_lab.setObjectName(_fromUtf8("prot_sec_lab"))
        self.horizontalLayout_3.addWidget(self.prot_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lip_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lip_lab.sizePolicy().hasHeightForWidth())
        self.lip_lab.setSizePolicy(sizePolicy)
        self.lip_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.lip_lab.setMaximumSize(QtCore.QSize(100, 25))
        self.lip_lab.setObjectName(_fromUtf8("lip_lab"))
        self.horizontalLayout_4.addWidget(self.lip_lab)
        self.lip_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lip_sec_lab.sizePolicy().hasHeightForWidth())
        self.lip_sec_lab.setSizePolicy(sizePolicy)
        self.lip_sec_lab.setMinimumSize(QtCore.QSize(0, 25))
        self.lip_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lip_sec_lab.setObjectName(_fromUtf8("lip_sec_lab"))
        self.horizontalLayout_4.addWidget(self.lip_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.carb_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carb_lab.sizePolicy().hasHeightForWidth())
        self.carb_lab.setSizePolicy(sizePolicy)
        self.carb_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.carb_lab.setMaximumSize(QtCore.QSize(100, 25))
        self.carb_lab.setObjectName(_fromUtf8("carb_lab"))
        self.horizontalLayout_5.addWidget(self.carb_lab)
        self.carb_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carb_sec_lab.sizePolicy().hasHeightForWidth())
        self.carb_sec_lab.setSizePolicy(sizePolicy)
        self.carb_sec_lab.setMinimumSize(QtCore.QSize(0, 25))
        self.carb_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.carb_sec_lab.setObjectName(_fromUtf8("carb_sec_lab"))
        self.horizontalLayout_5.addWidget(self.carb_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ccal_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccal_lab.sizePolicy().hasHeightForWidth())
        self.ccal_lab.setSizePolicy(sizePolicy)
        self.ccal_lab.setMinimumSize(QtCore.QSize(150, 25))
        self.ccal_lab.setMaximumSize(QtCore.QSize(150, 25))
        self.ccal_lab.setObjectName(_fromUtf8("ccal_lab"))
        self.horizontalLayout_6.addWidget(self.ccal_lab)
        self.ccal_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccal_sec_lab.sizePolicy().hasHeightForWidth())
        self.ccal_sec_lab.setSizePolicy(sizePolicy)
        self.ccal_sec_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.ccal_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ccal_sec_lab.setObjectName(_fromUtf8("ccal_sec_lab"))
        self.horizontalLayout_6.addWidget(self.ccal_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.glyc_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glyc_lab.sizePolicy().hasHeightForWidth())
        self.glyc_lab.setSizePolicy(sizePolicy)
        self.glyc_lab.setMinimumSize(QtCore.QSize(150, 25))
        self.glyc_lab.setMaximumSize(QtCore.QSize(150, 25))
        self.glyc_lab.setObjectName(_fromUtf8("glyc_lab"))
        self.horizontalLayout_7.addWidget(self.glyc_lab)
        self.glyc_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glyc_sec_lab.sizePolicy().hasHeightForWidth())
        self.glyc_sec_lab.setSizePolicy(sizePolicy)
        self.glyc_sec_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.glyc_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.glyc_sec_lab.setObjectName(_fromUtf8("glyc_sec_lab"))
        self.horizontalLayout_7.addWidget(self.glyc_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.searchwinbut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchwinbut.sizePolicy().hasHeightForWidth())
        self.searchwinbut.setSizePolicy(sizePolicy)
        self.searchwinbut.setMinimumSize(QtCore.QSize(100, 25))
        self.searchwinbut.setMaximumSize(QtCore.QSize(100, 25))
        self.searchwinbut.setDefault(True)
        self.searchwinbut.setObjectName(_fromUtf8("searchwinbut"))
        self.horizontalLayout_8.addWidget(self.searchwinbut)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.addbut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addbut.sizePolicy().hasHeightForWidth())
        self.addbut.setSizePolicy(sizePolicy)
        self.addbut.setMinimumSize(QtCore.QSize(100, 25))
        self.addbut.setMaximumSize(QtCore.QSize(100, 25))
        self.addbut.setDefault(True)
        self.addbut.setObjectName(_fromUtf8("addbut"))
        self.horizontalLayout_8.addWidget(self.addbut)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.text_selected = QtGui.QTextBrowser(self.centralwidget)
        self.text_selected.setMinimumSize(QtCore.QSize(381, 141))
        self.text_selected.setObjectName(_fromUtf8("text_selected"))
        self.gridLayout.addWidget(self.text_selected, 8, 0, 1, 1)
        self.total_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_lab.sizePolicy().hasHeightForWidth())
        self.total_lab.setSizePolicy(sizePolicy)
        self.total_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.total_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.total_lab.setObjectName(_fromUtf8("total_lab"))
        self.gridLayout.addWidget(self.total_lab, 9, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.tot_prot_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tot_prot_lab.sizePolicy().hasHeightForWidth())
        self.tot_prot_lab.setSizePolicy(sizePolicy)
        self.tot_prot_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.tot_prot_lab.setMaximumSize(QtCore.QSize(100, 25))
        self.tot_prot_lab.setObjectName(_fromUtf8("tot_prot_lab"))
        self.horizontalLayout_9.addWidget(self.tot_prot_lab)
        self.tot_prot_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tot_prot_sec_lab.sizePolicy().hasHeightForWidth())
        self.tot_prot_sec_lab.setSizePolicy(sizePolicy)
        self.tot_prot_sec_lab.setMinimumSize(QtCore.QSize(0, 25))
        self.tot_prot_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tot_prot_sec_lab.setObjectName(_fromUtf8("tot_prot_sec_lab"))
        self.horizontalLayout_9.addWidget(self.tot_prot_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_9, 10, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.tot_lip_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tot_lip_lab.sizePolicy().hasHeightForWidth())
        self.tot_lip_lab.setSizePolicy(sizePolicy)
        self.tot_lip_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.tot_lip_lab.setMaximumSize(QtCore.QSize(100, 25))
        self.tot_lip_lab.setObjectName(_fromUtf8("tot_lip_lab"))
        self.horizontalLayout_10.addWidget(self.tot_lip_lab)
        self.tot_lip_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tot_lip_sec_lab.sizePolicy().hasHeightForWidth())
        self.tot_lip_sec_lab.setSizePolicy(sizePolicy)
        self.tot_lip_sec_lab.setMinimumSize(QtCore.QSize(0, 25))
        self.tot_lip_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tot_lip_sec_lab.setObjectName(_fromUtf8("tot_lip_sec_lab"))
        self.horizontalLayout_10.addWidget(self.tot_lip_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_10, 11, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.tot_carb_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tot_carb_lab.sizePolicy().hasHeightForWidth())
        self.tot_carb_lab.setSizePolicy(sizePolicy)
        self.tot_carb_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.tot_carb_lab.setMaximumSize(QtCore.QSize(100, 25))
        self.tot_carb_lab.setObjectName(_fromUtf8("tot_carb_lab"))
        self.horizontalLayout_11.addWidget(self.tot_carb_lab)
        self.tot_carb_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tot_carb_sec_lab.sizePolicy().hasHeightForWidth())
        self.tot_carb_sec_lab.setSizePolicy(sizePolicy)
        self.tot_carb_sec_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.tot_carb_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tot_carb_sec_lab.setObjectName(_fromUtf8("tot_carb_sec_lab"))
        self.horizontalLayout_11.addWidget(self.tot_carb_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_11, 12, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.tot_ccal_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tot_ccal_lab.sizePolicy().hasHeightForWidth())
        self.tot_ccal_lab.setSizePolicy(sizePolicy)
        self.tot_ccal_lab.setMinimumSize(QtCore.QSize(150, 25))
        self.tot_ccal_lab.setMaximumSize(QtCore.QSize(150, 25))
        self.tot_ccal_lab.setObjectName(_fromUtf8("tot_ccal_lab"))
        self.horizontalLayout_12.addWidget(self.tot_ccal_lab)
        self.tot_ccal_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tot_ccal_sec_lab.sizePolicy().hasHeightForWidth())
        self.tot_ccal_sec_lab.setSizePolicy(sizePolicy)
        self.tot_ccal_sec_lab.setMinimumSize(QtCore.QSize(0, 25))
        self.tot_ccal_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tot_ccal_sec_lab.setObjectName(_fromUtf8("tot_ccal_sec_lab"))
        self.horizontalLayout_12.addWidget(self.tot_ccal_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_12, 13, 0, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.savebut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savebut.sizePolicy().hasHeightForWidth())
        self.savebut.setSizePolicy(sizePolicy)
        self.savebut.setMinimumSize(QtCore.QSize(150, 25))
        self.savebut.setMaximumSize(QtCore.QSize(150, 25))
        self.savebut.setDefault(True)
        self.savebut.setObjectName(_fromUtf8("savebut"))
        self.horizontalLayout_13.addWidget(self.savebut)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.deletebut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deletebut.sizePolicy().hasHeightForWidth())
        self.deletebut.setSizePolicy(sizePolicy)
        self.deletebut.setMinimumSize(QtCore.QSize(100, 25))
        self.deletebut.setMaximumSize(QtCore.QSize(100, 25))
        self.deletebut.setDefault(True)
        self.deletebut.setObjectName(_fromUtf8("deletebut"))
        self.horizontalLayout_13.addWidget(self.deletebut)
        self.exitbut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitbut.sizePolicy().hasHeightForWidth())
        self.exitbut.setSizePolicy(sizePolicy)
        self.exitbut.setMinimumSize(QtCore.QSize(100, 25))
        self.exitbut.setMaximumSize(QtCore.QSize(100, 25))
        self.exitbut.setDefault(True)
        self.exitbut.setObjectName(_fromUtf8("exitbut"))
        self.horizontalLayout_13.addWidget(self.exitbut)
        self.gridLayout.addLayout(self.horizontalLayout_13, 14, 0, 1, 1)
        Calc_Window.setCentralWidget(self.centralwidget)

        #self.retranslateUi(Calc_Window)
        QtCore.QMetaObject.connectSlotsByName(Calc_Window)

    def retranslateUi(self, Calc_Window):
        Calc_Window.setWindowTitle(_translate("Calc_Window", "Расчитать", None))
        self.search_lab.setText(_translate("Calc_Window", "Продукт", None))
        self.mass_lab.setText(_translate("Calc_Window", "Масса, г", None))
        self.substitutebut.setText(_translate("Calc_Window", "Подставить", None))
        self.searchbut.setText(_translate("Calc_Window", "Искать", None))
        self.prot_lab.setText(_translate("Calc_Window", "Белки", None))
        self.prot_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.lip_lab.setText(_translate("Calc_Window", "Жиры", None))
        self.lip_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.carb_lab.setText(_translate("Calc_Window", "Углеводы", None))
        self.carb_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.ccal_lab.setText(_translate("Calc_Window", "Калорийность, ккал", None))
        self.ccal_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.glyc_lab.setText(_translate("Calc_Window", "Гликемический индекс", None))
        self.glyc_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.searchwinbut.setText(_translate("Calc_Window", "Окно поиска", None))
        self.addbut.setText(_translate("Calc_Window", "Добавить", None))
        self.total_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"center\">Всего:</p></body></html>", None))
        self.tot_prot_lab.setText(_translate("Calc_Window", "Белки", None))
        self.tot_prot_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.tot_lip_lab.setText(_translate("Calc_Window", "Жиры", None))
        self.tot_lip_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.tot_carb_lab.setText(_translate("Calc_Window", "Углеводы", None))
        self.tot_carb_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.tot_ccal_lab.setText(_translate("Calc_Window", "Калорийность, ккал", None))
        self.tot_ccal_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.savebut.setText(_translate("Calc_Window", "Сохранить в файл", None))
        self.deletebut.setText(_translate("Calc_Window", "Очистить", None))
        self.exitbut.setText(_translate("Calc_Window", "Закрыть", None))

