# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcwin.ui'
#
# Created: Fri Jan 11 17:33:39 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Calc_Window(object):
    def setupUi(self, Calc_Window):
        Calc_Window.setObjectName(_fromUtf8("Calc_Window"))
        Calc_Window.resize(403, 469)
        self.centralwidget = QtGui.QWidget(Calc_Window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.search_lab = QtGui.QLabel(self.centralwidget)
        self.search_lab.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.search_lab.setObjectName(_fromUtf8("search_lab"))
        self.search_line = QtGui.QLineEdit(self.centralwidget)
        self.search_line.setGeometry(QtCore.QRect(90, 10, 301, 23))
        self.search_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_line.setObjectName(_fromUtf8("search_line"))
        self.searchbut = QtGui.QPushButton(self.centralwidget)
        self.searchbut.setGeometry(QtCore.QRect(310, 35, 81, 24))
        self.searchbut.setDefault(True)
        self.searchbut.setObjectName(_fromUtf8("searchbut"))
        self.prot_lab = QtGui.QLabel(self.centralwidget)
        self.prot_lab.setGeometry(QtCore.QRect(10, 60, 151, 21))
        self.prot_lab.setObjectName(_fromUtf8("prot_lab"))
        self.lip_lab = QtGui.QLabel(self.centralwidget)
        self.lip_lab.setGeometry(QtCore.QRect(10, 80, 151, 21))
        self.lip_lab.setObjectName(_fromUtf8("lip_lab"))
        self.prot_sec_lab = QtGui.QLabel(self.centralwidget)
        self.prot_sec_lab.setGeometry(QtCore.QRect(240, 60, 151, 21))
        self.prot_sec_lab.setObjectName(_fromUtf8("prot_sec_lab"))
        self.lip_sec_lab = QtGui.QLabel(self.centralwidget)
        self.lip_sec_lab.setGeometry(QtCore.QRect(240, 80, 151, 21))
        self.lip_sec_lab.setObjectName(_fromUtf8("lip_sec_lab"))
        self.carb_lab = QtGui.QLabel(self.centralwidget)
        self.carb_lab.setGeometry(QtCore.QRect(10, 100, 151, 21))
        self.carb_lab.setObjectName(_fromUtf8("carb_lab"))
        self.ccal_sec_lab = QtGui.QLabel(self.centralwidget)
        self.ccal_sec_lab.setGeometry(QtCore.QRect(240, 120, 151, 21))
        self.ccal_sec_lab.setObjectName(_fromUtf8("ccal_sec_lab"))
        self.carb_sec_lab = QtGui.QLabel(self.centralwidget)
        self.carb_sec_lab.setGeometry(QtCore.QRect(240, 100, 151, 21))
        self.carb_sec_lab.setObjectName(_fromUtf8("carb_sec_lab"))
        self.ccal_lab = QtGui.QLabel(self.centralwidget)
        self.ccal_lab.setGeometry(QtCore.QRect(10, 120, 151, 21))
        self.ccal_lab.setObjectName(_fromUtf8("ccal_lab"))
        self.glyc_lab = QtGui.QLabel(self.centralwidget)
        self.glyc_lab.setGeometry(QtCore.QRect(10, 140, 151, 21))
        self.glyc_lab.setObjectName(_fromUtf8("glyc_lab"))
        self.glyc_sec_lab = QtGui.QLabel(self.centralwidget)
        self.glyc_sec_lab.setGeometry(QtCore.QRect(240, 140, 151, 21))
        self.glyc_sec_lab.setObjectName(_fromUtf8("glyc_sec_lab"))
        self.addbut = QtGui.QPushButton(self.centralwidget)
        self.addbut.setGeometry(QtCore.QRect(300, 160, 91, 24))
        self.addbut.setDefault(True)
        self.addbut.setObjectName(_fromUtf8("addbut"))
        self.mass_line = QtGui.QLineEdit(self.centralwidget)
        self.mass_line.setGeometry(QtCore.QRect(90, 35, 211, 23))
        self.mass_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mass_line.setObjectName(_fromUtf8("mass_line"))
        self.mass_lab = QtGui.QLabel(self.centralwidget)
        self.mass_lab.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.mass_lab.setObjectName(_fromUtf8("mass_lab"))
        self.tot_ccal_lab = QtGui.QLabel(self.centralwidget)
        self.tot_ccal_lab.setGeometry(QtCore.QRect(10, 410, 151, 21))
        self.tot_ccal_lab.setObjectName(_fromUtf8("tot_ccal_lab"))
        self.tot_lip_lab = QtGui.QLabel(self.centralwidget)
        self.tot_lip_lab.setGeometry(QtCore.QRect(10, 370, 151, 21))
        self.tot_lip_lab.setObjectName(_fromUtf8("tot_lip_lab"))
        self.tot_prot_lab = QtGui.QLabel(self.centralwidget)
        self.tot_prot_lab.setGeometry(QtCore.QRect(10, 350, 151, 21))
        self.tot_prot_lab.setObjectName(_fromUtf8("tot_prot_lab"))
        self.tot_prot_sec_lab = QtGui.QLabel(self.centralwidget)
        self.tot_prot_sec_lab.setGeometry(QtCore.QRect(240, 350, 151, 21))
        self.tot_prot_sec_lab.setObjectName(_fromUtf8("tot_prot_sec_lab"))
        self.tot_lip_sec_lab = QtGui.QLabel(self.centralwidget)
        self.tot_lip_sec_lab.setGeometry(QtCore.QRect(240, 370, 151, 21))
        self.tot_lip_sec_lab.setObjectName(_fromUtf8("tot_lip_sec_lab"))
        self.tot_ccal_sec_lab = QtGui.QLabel(self.centralwidget)
        self.tot_ccal_sec_lab.setGeometry(QtCore.QRect(240, 410, 151, 21))
        self.tot_ccal_sec_lab.setObjectName(_fromUtf8("tot_ccal_sec_lab"))
        self.tot_carb_sec_lab = QtGui.QLabel(self.centralwidget)
        self.tot_carb_sec_lab.setGeometry(QtCore.QRect(240, 390, 151, 21))
        self.tot_carb_sec_lab.setObjectName(_fromUtf8("tot_carb_sec_lab"))
        self.tot_carb_lab = QtGui.QLabel(self.centralwidget)
        self.tot_carb_lab.setGeometry(QtCore.QRect(10, 390, 151, 21))
        self.tot_carb_lab.setObjectName(_fromUtf8("tot_carb_lab"))
        self.total_lab = QtGui.QLabel(self.centralwidget)
        self.total_lab.setGeometry(QtCore.QRect(10, 330, 381, 21))
        self.total_lab.setObjectName(_fromUtf8("total_lab"))
        self.savebut = QtGui.QPushButton(self.centralwidget)
        self.savebut.setGeometry(QtCore.QRect(10, 440, 131, 24))
        self.savebut.setDefault(True)
        self.savebut.setObjectName(_fromUtf8("savebut"))
        self.exitbut = QtGui.QPushButton(self.centralwidget)
        self.exitbut.setGeometry(QtCore.QRect(300, 440, 91, 24))
        self.exitbut.setDefault(True)
        self.exitbut.setObjectName(_fromUtf8("exitbut"))
        self.text_selected = QtGui.QTextBrowser(self.centralwidget)
        self.text_selected.setGeometry(QtCore.QRect(10, 190, 381, 141))
        self.text_selected.setObjectName(_fromUtf8("text_selected"))
        self.deletebut = QtGui.QPushButton(self.centralwidget)
        self.deletebut.setGeometry(QtCore.QRect(205, 440, 91, 24))
        self.deletebut.setDefault(True)
        self.deletebut.setObjectName(_fromUtf8("deletebut"))
        Calc_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calc_Window)
        QtCore.QObject.connect(self.exitbut, QtCore.SIGNAL(_fromUtf8("clicked()")), Calc_Window.close)
        QtCore.QMetaObject.connectSlotsByName(Calc_Window)
        Calc_Window.setTabOrder(self.search_line, self.mass_line)
        Calc_Window.setTabOrder(self.mass_line, self.searchbut)
        Calc_Window.setTabOrder(self.searchbut, self.addbut)
        Calc_Window.setTabOrder(self.addbut, self.text_selected)
        Calc_Window.setTabOrder(self.text_selected, self.savebut)
        Calc_Window.setTabOrder(self.savebut, self.deletebut)
        Calc_Window.setTabOrder(self.deletebut, self.exitbut)

    def retranslateUi(self, Calc_Window):
        Calc_Window.setWindowTitle(_translate("Calc_Window", "Расчитать", None))
        self.search_lab.setText(_translate("Calc_Window", "Продукт", None))
        self.searchbut.setText(_translate("Calc_Window", "Искать", None))
        self.prot_lab.setText(_translate("Calc_Window", "Белки", None))
        self.lip_lab.setText(_translate("Calc_Window", "Жиры", None))
        self.prot_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.lip_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.carb_lab.setText(_translate("Calc_Window", "Углеводы", None))
        self.ccal_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.carb_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.ccal_lab.setText(_translate("Calc_Window", "Калорийность, ккал", None))
        self.glyc_lab.setText(_translate("Calc_Window", "Гликемический индекс", None))
        self.glyc_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.addbut.setText(_translate("Calc_Window", "Добавить", None))
        self.mass_lab.setText(_translate("Calc_Window", "Масса, г", None))
        self.tot_ccal_lab.setText(_translate("Calc_Window", "Калорийность, ккал", None))
        self.tot_lip_lab.setText(_translate("Calc_Window", "Жиры", None))
        self.tot_prot_lab.setText(_translate("Calc_Window", "Белки", None))
        self.tot_prot_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.tot_lip_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.tot_ccal_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.tot_carb_sec_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.tot_carb_lab.setText(_translate("Calc_Window", "Углеводы", None))
        self.total_lab.setText(_translate("Calc_Window", "<html><head/><body><p align=\"center\">Всего:</p></body></html>", None))
        self.savebut.setText(_translate("Calc_Window", "Сохранить в файл", None))
        self.exitbut.setText(_translate("Calc_Window", "Закрыть", None))
        self.deletebut.setText(_translate("Calc_Window", "Очистить", None))

