# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit.ui'
#
# Created: Sat Apr 13 17:17:24 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Edit(object):
    def setupUi(self, Edit):
        Edit.setObjectName(_fromUtf8("Edit"))
        Edit.resize(336, 256)
        Edit.setMinimumSize(QtCore.QSize(336, 256))
        self.centralwidget = QtGui.QWidget(Edit)
        self.centralwidget.setMinimumSize(QtCore.QSize(336, 256))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.subs_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subs_lab.sizePolicy().hasHeightForWidth())
        self.subs_lab.setSizePolicy(sizePolicy)
        self.subs_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.subs_lab.setMaximumSize(QtCore.QSize(100, 25))
        self.subs_lab.setObjectName(_fromUtf8("subs_lab"))
        self.horizontalLayout.addWidget(self.subs_lab)
        self.search_line = QtGui.QLineEdit(self.centralwidget)
        self.search_line.setMinimumSize(QtCore.QSize(100, 25))
        self.search_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.search_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_line.setObjectName(_fromUtf8("search_line"))
        self.horizontalLayout.addWidget(self.search_line)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.searchbut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchbut.sizePolicy().hasHeightForWidth())
        self.searchbut.setSizePolicy(sizePolicy)
        self.searchbut.setMinimumSize(QtCore.QSize(100, 25))
        self.searchbut.setMaximumSize(QtCore.QSize(100, 25))
        self.searchbut.setDefault(True)
        self.searchbut.setObjectName(_fromUtf8("searchbut"))
        self.horizontalLayout_2.addWidget(self.searchbut)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.substitutebut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.substitutebut.sizePolicy().hasHeightForWidth())
        self.substitutebut.setSizePolicy(sizePolicy)
        self.substitutebut.setMinimumSize(QtCore.QSize(100, 25))
        self.substitutebut.setMaximumSize(QtCore.QSize(100, 25))
        self.substitutebut.setDefault(True)
        self.substitutebut.setObjectName(_fromUtf8("substitutebut"))
        self.horizontalLayout_2.addWidget(self.substitutebut)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.prot_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prot_lab.sizePolicy().hasHeightForWidth())
        self.prot_lab.setSizePolicy(sizePolicy)
        self.prot_lab.setMinimumSize(QtCore.QSize(150, 25))
        self.prot_lab.setMaximumSize(QtCore.QSize(150, 25))
        self.prot_lab.setObjectName(_fromUtf8("prot_lab"))
        self.horizontalLayout_3.addWidget(self.prot_lab)
        self.prot_line = QtGui.QLineEdit(self.centralwidget)
        self.prot_line.setMinimumSize(QtCore.QSize(100, 25))
        self.prot_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.prot_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prot_line.setObjectName(_fromUtf8("prot_line"))
        self.horizontalLayout_3.addWidget(self.prot_line)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lip_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lip_lab.sizePolicy().hasHeightForWidth())
        self.lip_lab.setSizePolicy(sizePolicy)
        self.lip_lab.setMinimumSize(QtCore.QSize(150, 25))
        self.lip_lab.setMaximumSize(QtCore.QSize(150, 25))
        self.lip_lab.setObjectName(_fromUtf8("lip_lab"))
        self.horizontalLayout_4.addWidget(self.lip_lab)
        self.lip_line = QtGui.QLineEdit(self.centralwidget)
        self.lip_line.setMinimumSize(QtCore.QSize(100, 25))
        self.lip_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lip_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lip_line.setObjectName(_fromUtf8("lip_line"))
        self.horizontalLayout_4.addWidget(self.lip_line)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.carb_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carb_lab.sizePolicy().hasHeightForWidth())
        self.carb_lab.setSizePolicy(sizePolicy)
        self.carb_lab.setMinimumSize(QtCore.QSize(150, 25))
        self.carb_lab.setMaximumSize(QtCore.QSize(150, 25))
        self.carb_lab.setObjectName(_fromUtf8("carb_lab"))
        self.horizontalLayout_5.addWidget(self.carb_lab)
        self.carb_line = QtGui.QLineEdit(self.centralwidget)
        self.carb_line.setMinimumSize(QtCore.QSize(100, 25))
        self.carb_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.carb_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.carb_line.setObjectName(_fromUtf8("carb_line"))
        self.horizontalLayout_5.addWidget(self.carb_line)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ccal_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccal_lab.sizePolicy().hasHeightForWidth())
        self.ccal_lab.setSizePolicy(sizePolicy)
        self.ccal_lab.setMinimumSize(QtCore.QSize(150, 25))
        self.ccal_lab.setMaximumSize(QtCore.QSize(150, 25))
        self.ccal_lab.setObjectName(_fromUtf8("ccal_lab"))
        self.horizontalLayout_6.addWidget(self.ccal_lab)
        self.ccal_line = QtGui.QLineEdit(self.centralwidget)
        self.ccal_line.setMinimumSize(QtCore.QSize(100, 25))
        self.ccal_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ccal_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ccal_line.setObjectName(_fromUtf8("ccal_line"))
        self.horizontalLayout_6.addWidget(self.ccal_line)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.glyc_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glyc_lab.sizePolicy().hasHeightForWidth())
        self.glyc_lab.setSizePolicy(sizePolicy)
        self.glyc_lab.setMinimumSize(QtCore.QSize(150, 25))
        self.glyc_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.glyc_lab.setObjectName(_fromUtf8("glyc_lab"))
        self.horizontalLayout_7.addWidget(self.glyc_lab)
        self.glyc_line = QtGui.QLineEdit(self.centralwidget)
        self.glyc_line.setMinimumSize(QtCore.QSize(100, 25))
        self.glyc_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.glyc_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.glyc_line.setObjectName(_fromUtf8("glyc_line"))
        self.horizontalLayout_7.addWidget(self.glyc_line)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.deletebut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deletebut.sizePolicy().hasHeightForWidth())
        self.deletebut.setSizePolicy(sizePolicy)
        self.deletebut.setMinimumSize(QtCore.QSize(100, 25))
        self.deletebut.setMaximumSize(QtCore.QSize(100, 25))
        self.deletebut.setDefault(True)
        self.deletebut.setObjectName(_fromUtf8("deletebut"))
        self.horizontalLayout_8.addWidget(self.deletebut)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.okbut = QtGui.QPushButton(self.centralwidget)
        self.okbut.setMinimumSize(QtCore.QSize(100, 25))
        self.okbut.setMaximumSize(QtCore.QSize(100, 25))
        self.okbut.setDefault(True)
        self.okbut.setObjectName(_fromUtf8("okbut"))
        self.horizontalLayout_8.addWidget(self.okbut)
        self.cancelbut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelbut.sizePolicy().hasHeightForWidth())
        self.cancelbut.setSizePolicy(sizePolicy)
        self.cancelbut.setMinimumSize(QtCore.QSize(100, 25))
        self.cancelbut.setMaximumSize(QtCore.QSize(100, 25))
        self.cancelbut.setDefault(True)
        self.cancelbut.setObjectName(_fromUtf8("cancelbut"))
        self.horizontalLayout_8.addWidget(self.cancelbut)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 8, 0, 1, 1)
        Edit.setCentralWidget(self.centralwidget)

        self.retranslateUi(Edit)
        QtCore.QMetaObject.connectSlotsByName(Edit)

    def retranslateUi(self, Edit):
        Edit.setWindowTitle(_translate("Edit", "Редактировать", None))
        self.subs_lab.setText(_translate("Edit", "Продукт", None))
        self.searchbut.setText(_translate("Edit", "Окно поиска", None))
        self.substitutebut.setText(_translate("Edit", "Подставить", None))
        self.prot_lab.setText(_translate("Edit", "Белки", None))
        self.lip_lab.setText(_translate("Edit", "Жиры", None))
        self.carb_lab.setText(_translate("Edit", "Углеводы", None))
        self.ccal_lab.setText(_translate("Edit", "Калорийность, ккал", None))
        self.glyc_lab.setText(_translate("Edit", "Гликемический индекс", None))
        self.deletebut.setText(_translate("Edit", "Удалить", None))
        self.okbut.setText(_translate("Edit", "Ok", None))
        self.cancelbut.setText(_translate("Edit", "Отмена", None))

