.TH food_gui 1  "January 17, 2013" "version 1.2.0" "USER COMMANDS"
.SH NAME
food_gui
.SH SYNOPSIS
.B food_gui
.SH DESCRIPTION
food_gui is a simple program-calculator used self database and written on Python,
that calculates proteins, fats, carbohydrates, food energy and glycemic index
eaten food.
.SH FILES
~/.config/food_gui/food_gui.ini - configuration file
.PP
db.dat - database
.SH AUTHOR
Evgeniy Alexeev aka arcanis (esalexeev (at) gmail.com)

