# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created: Fri Jan 11 20:26:02 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Food(object):
    def setupUi(self, Food):
        Food.setObjectName(_fromUtf8("Food"))
        Food.resize(421, 212)
        self.centralwidget = QtGui.QWidget(Food)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.search_line = QtGui.QLineEdit(self.centralwidget)
        self.search_line.setGeometry(QtCore.QRect(10, 10, 221, 23))
        self.search_line.setText(_fromUtf8(""))
        self.search_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_line.setObjectName(_fromUtf8("search_line"))
        self.searchbut = QtGui.QPushButton(self.centralwidget)
        self.searchbut.setGeometry(QtCore.QRect(318, 38, 91, 24))
        self.searchbut.setDefault(True)
        self.searchbut.setObjectName(_fromUtf8("searchbut"))
        self.mass_line = QtGui.QLineEdit(self.centralwidget)
        self.mass_line.setGeometry(QtCore.QRect(310, 10, 101, 23))
        self.mass_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mass_line.setObjectName(_fromUtf8("mass_line"))
        self.mass_lab = QtGui.QLabel(self.centralwidget)
        self.mass_lab.setGeometry(QtCore.QRect(244, 10, 61, 21))
        self.mass_lab.setObjectName(_fromUtf8("mass_lab"))
        self.prot_lab = QtGui.QLabel(self.centralwidget)
        self.prot_lab.setGeometry(QtCore.QRect(10, 65, 151, 21))
        self.prot_lab.setObjectName(_fromUtf8("prot_lab"))
        self.lip_lab = QtGui.QLabel(self.centralwidget)
        self.lip_lab.setGeometry(QtCore.QRect(10, 85, 151, 21))
        self.lip_lab.setObjectName(_fromUtf8("lip_lab"))
        self.carb_lab = QtGui.QLabel(self.centralwidget)
        self.carb_lab.setGeometry(QtCore.QRect(10, 105, 151, 21))
        self.carb_lab.setObjectName(_fromUtf8("carb_lab"))
        self.ccal_lab = QtGui.QLabel(self.centralwidget)
        self.ccal_lab.setGeometry(QtCore.QRect(10, 125, 151, 21))
        self.ccal_lab.setObjectName(_fromUtf8("ccal_lab"))
        self.glyc_lab = QtGui.QLabel(self.centralwidget)
        self.glyc_lab.setGeometry(QtCore.QRect(10, 145, 151, 21))
        self.glyc_lab.setObjectName(_fromUtf8("glyc_lab"))
        self.prot_sec_lab = QtGui.QLabel(self.centralwidget)
        self.prot_sec_lab.setGeometry(QtCore.QRect(230, 65, 151, 21))
        self.prot_sec_lab.setObjectName(_fromUtf8("prot_sec_lab"))
        self.lip_sec_lab = QtGui.QLabel(self.centralwidget)
        self.lip_sec_lab.setGeometry(QtCore.QRect(230, 85, 151, 21))
        self.lip_sec_lab.setObjectName(_fromUtf8("lip_sec_lab"))
        self.carb_sec_lab = QtGui.QLabel(self.centralwidget)
        self.carb_sec_lab.setGeometry(QtCore.QRect(230, 105, 151, 21))
        self.carb_sec_lab.setObjectName(_fromUtf8("carb_sec_lab"))
        self.ccal_sec_lab = QtGui.QLabel(self.centralwidget)
        self.ccal_sec_lab.setGeometry(QtCore.QRect(230, 125, 151, 21))
        self.ccal_sec_lab.setObjectName(_fromUtf8("ccal_sec_lab"))
        self.glyc_sec_lab = QtGui.QLabel(self.centralwidget)
        self.glyc_sec_lab.setGeometry(QtCore.QRect(230, 145, 151, 21))
        self.glyc_sec_lab.setObjectName(_fromUtf8("glyc_sec_lab"))
        Food.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Food)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        Food.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Food)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Food.setStatusBar(self.statusbar)
        self.menu_add = QtGui.QAction(Food)
        self.menu_add.setObjectName(_fromUtf8("menu_add"))
        self.menu_edit = QtGui.QAction(Food)
        self.menu_edit.setObjectName(_fromUtf8("menu_edit"))
        self.menu_create = QtGui.QAction(Food)
        self.menu_create.setObjectName(_fromUtf8("menu_create"))
        self.menu_dbch = QtGui.QAction(Food)
        self.menu_dbch.setObjectName(_fromUtf8("menu_dbch"))
        self.menu_dbcp = QtGui.QAction(Food)
        self.menu_dbcp.setObjectName(_fromUtf8("menu_dbcp"))
        self.menu_exit = QtGui.QAction(Food)
        self.menu_exit.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.menu_exit.setMenuRole(QtGui.QAction.QuitRole)
        self.menu_exit.setPriority(QtGui.QAction.HighPriority)
        self.menu_exit.setObjectName(_fromUtf8("menu_exit"))
        self.menu_about = QtGui.QAction(Food)
        self.menu_about.setObjectName(_fromUtf8("menu_about"))
        self.menu_calc = QtGui.QAction(Food)
        self.menu_calc.setObjectName(_fromUtf8("menu_calc"))
        self.menu_dbsel = QtGui.QAction(Food)
        self.menu_dbsel.setObjectName(_fromUtf8("menu_dbsel"))
        self.menu.addAction(self.menu_add)
        self.menu.addAction(self.menu_edit)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_create)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_dbsel)
        self.menu.addAction(self.menu_dbcp)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_exit)
        self.menu_2.addAction(self.menu_about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(Food)
        QtCore.QObject.connect(self.menu_exit, QtCore.SIGNAL(_fromUtf8("triggered()")), Food.close)
        QtCore.QMetaObject.connectSlotsByName(Food)
        Food.setTabOrder(self.search_line, self.mass_line)
        Food.setTabOrder(self.mass_line, self.searchbut)

    def retranslateUi(self, Food):
        Food.setWindowTitle(_translate("Food", "Food", None))
        self.searchbut.setText(_translate("Food", "Посчитать", None))
        self.mass_lab.setText(_translate("Food", "Масса, г", None))
        self.prot_lab.setText(_translate("Food", "Белки", None))
        self.lip_lab.setText(_translate("Food", "Жиры", None))
        self.carb_lab.setText(_translate("Food", "Углеводы", None))
        self.ccal_lab.setText(_translate("Food", "Калорийность, ккал", None))
        self.glyc_lab.setText(_translate("Food", "Гликемический индекс", None))
        self.prot_sec_lab.setText(_translate("Food", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.lip_sec_lab.setText(_translate("Food", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.carb_sec_lab.setText(_translate("Food", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.ccal_sec_lab.setText(_translate("Food", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.glyc_sec_lab.setText(_translate("Food", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.menu.setTitle(_translate("Food", "&Меню", None))
        self.menu_2.setTitle(_translate("Food", "&Справка", None))
        self.menu_add.setText(_translate("Food", "&Добавить продукт в базу данных", None))
        self.menu_add.setShortcut(_translate("Food", "Ctrl+A", None))
        self.menu_edit.setText(_translate("Food", "&Редактировать базу данных", None))
        self.menu_edit.setShortcut(_translate("Food", "Ctrl+E", None))
        self.menu_create.setText(_translate("Food", "&Создать меню", None))
        self.menu_create.setShortcut(_translate("Food", "Ctrl+N", None))
        self.menu_dbch.setText(_translate("Food", "&Выбрать базу данных", None))
        self.menu_dbcp.setText(_translate("Food", "С&копировать базу данных", None))
        self.menu_exit.setText(_translate("Food", "&Выход", None))
        self.menu_exit.setShortcut(_translate("Food", "Ctrl+Q", None))
        self.menu_about.setText(_translate("Food", "&О программе", None))
        self.menu_about.setShortcut(_translate("Food", "F1", None))
        self.menu_calc.setText(_translate("Food", "Р&асчитать", None))
        self.menu_calc.setShortcut(_translate("Food", "Ctrl+C", None))
        self.menu_dbsel.setText(_translate("Food", "Выбрать базу данных", None))

