# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created: Sat Apr 13 17:32:17 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Food(object):
    def setupUi(self, Food):
        Food.setObjectName(_fromUtf8("Food"))
        Food.resize(421, 266)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Food.sizePolicy().hasHeightForWidth())
        Food.setSizePolicy(sizePolicy)
        Food.setMinimumSize(QtCore.QSize(421, 266))
        self.centralwidget = QtGui.QWidget(Food)
        self.centralwidget.setMinimumSize(QtCore.QSize(421, 225))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.search_line = QtGui.QLineEdit(self.centralwidget)
        self.search_line.setMinimumSize(QtCore.QSize(100, 25))
        self.search_line.setMaximumSize(QtCore.QSize(16777215, 25))
        self.search_line.setText(_fromUtf8(""))
        self.search_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_line.setObjectName(_fromUtf8("search_line"))
        self.horizontalLayout.addWidget(self.search_line)
        self.mass_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mass_lab.sizePolicy().hasHeightForWidth())
        self.mass_lab.setSizePolicy(sizePolicy)
        self.mass_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.mass_lab.setMaximumSize(QtCore.QSize(100, 25))
        self.mass_lab.setObjectName(_fromUtf8("mass_lab"))
        self.horizontalLayout.addWidget(self.mass_lab)
        self.mass_line = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mass_line.sizePolicy().hasHeightForWidth())
        self.mass_line.setSizePolicy(sizePolicy)
        self.mass_line.setMinimumSize(QtCore.QSize(100, 25))
        self.mass_line.setMaximumSize(QtCore.QSize(100, 25))
        self.mass_line.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.mass_line.setObjectName(_fromUtf8("mass_line"))
        self.horizontalLayout.addWidget(self.mass_line)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lip_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lip_lab.sizePolicy().hasHeightForWidth())
        self.lip_lab.setSizePolicy(sizePolicy)
        self.lip_lab.setMinimumSize(QtCore.QSize(175, 25))
        self.lip_lab.setMaximumSize(QtCore.QSize(175, 25))
        self.lip_lab.setObjectName(_fromUtf8("lip_lab"))
        self.horizontalLayout_4.addWidget(self.lip_lab)
        self.lip_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lip_sec_lab.sizePolicy().hasHeightForWidth())
        self.lip_sec_lab.setSizePolicy(sizePolicy)
        self.lip_sec_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.lip_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lip_sec_lab.setObjectName(_fromUtf8("lip_sec_lab"))
        self.horizontalLayout_4.addWidget(self.lip_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.ccal_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccal_lab.sizePolicy().hasHeightForWidth())
        self.ccal_lab.setSizePolicy(sizePolicy)
        self.ccal_lab.setMinimumSize(QtCore.QSize(175, 25))
        self.ccal_lab.setMaximumSize(QtCore.QSize(175, 25))
        self.ccal_lab.setObjectName(_fromUtf8("ccal_lab"))
        self.horizontalLayout_6.addWidget(self.ccal_lab)
        self.ccal_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccal_sec_lab.sizePolicy().hasHeightForWidth())
        self.ccal_sec_lab.setSizePolicy(sizePolicy)
        self.ccal_sec_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.ccal_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.ccal_sec_lab.setObjectName(_fromUtf8("ccal_sec_lab"))
        self.horizontalLayout_6.addWidget(self.ccal_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.carb_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carb_lab.sizePolicy().hasHeightForWidth())
        self.carb_lab.setSizePolicy(sizePolicy)
        self.carb_lab.setMinimumSize(QtCore.QSize(175, 25))
        self.carb_lab.setMaximumSize(QtCore.QSize(175, 25))
        self.carb_lab.setObjectName(_fromUtf8("carb_lab"))
        self.horizontalLayout_5.addWidget(self.carb_lab)
        self.carb_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.carb_sec_lab.sizePolicy().hasHeightForWidth())
        self.carb_sec_lab.setSizePolicy(sizePolicy)
        self.carb_sec_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.carb_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.carb_sec_lab.setObjectName(_fromUtf8("carb_sec_lab"))
        self.horizontalLayout_5.addWidget(self.carb_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.searchbut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchbut.sizePolicy().hasHeightForWidth())
        self.searchbut.setSizePolicy(sizePolicy)
        self.searchbut.setMinimumSize(QtCore.QSize(100, 25))
        self.searchbut.setMaximumSize(QtCore.QSize(100, 25))
        self.searchbut.setDefault(True)
        self.searchbut.setObjectName(_fromUtf8("searchbut"))
        self.horizontalLayout_2.addWidget(self.searchbut)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.substitutebut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.substitutebut.sizePolicy().hasHeightForWidth())
        self.substitutebut.setSizePolicy(sizePolicy)
        self.substitutebut.setMinimumSize(QtCore.QSize(100, 25))
        self.substitutebut.setMaximumSize(QtCore.QSize(100, 25))
        self.substitutebut.setDefault(True)
        self.substitutebut.setObjectName(_fromUtf8("substitutebut"))
        self.horizontalLayout_2.addWidget(self.substitutebut)
        self.calcbut = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcbut.sizePolicy().hasHeightForWidth())
        self.calcbut.setSizePolicy(sizePolicy)
        self.calcbut.setMinimumSize(QtCore.QSize(100, 25))
        self.calcbut.setMaximumSize(QtCore.QSize(100, 25))
        self.calcbut.setDefault(True)
        self.calcbut.setObjectName(_fromUtf8("calcbut"))
        self.horizontalLayout_2.addWidget(self.calcbut)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.prot_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prot_lab.sizePolicy().hasHeightForWidth())
        self.prot_lab.setSizePolicy(sizePolicy)
        self.prot_lab.setMinimumSize(QtCore.QSize(175, 25))
        self.prot_lab.setMaximumSize(QtCore.QSize(175, 25))
        self.prot_lab.setObjectName(_fromUtf8("prot_lab"))
        self.horizontalLayout_3.addWidget(self.prot_lab)
        self.prot_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prot_sec_lab.sizePolicy().hasHeightForWidth())
        self.prot_sec_lab.setSizePolicy(sizePolicy)
        self.prot_sec_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.prot_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.prot_sec_lab.setObjectName(_fromUtf8("prot_sec_lab"))
        self.horizontalLayout_3.addWidget(self.prot_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.glyc_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glyc_lab.sizePolicy().hasHeightForWidth())
        self.glyc_lab.setSizePolicy(sizePolicy)
        self.glyc_lab.setMinimumSize(QtCore.QSize(175, 25))
        self.glyc_lab.setMaximumSize(QtCore.QSize(175, 25))
        self.glyc_lab.setObjectName(_fromUtf8("glyc_lab"))
        self.horizontalLayout_7.addWidget(self.glyc_lab)
        self.glyc_sec_lab = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.glyc_sec_lab.sizePolicy().hasHeightForWidth())
        self.glyc_sec_lab.setSizePolicy(sizePolicy)
        self.glyc_sec_lab.setMinimumSize(QtCore.QSize(100, 25))
        self.glyc_sec_lab.setMaximumSize(QtCore.QSize(16777215, 25))
        self.glyc_sec_lab.setObjectName(_fromUtf8("glyc_sec_lab"))
        self.horizontalLayout_7.addWidget(self.glyc_sec_lab)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 2, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 111, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        Food.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Food)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        Food.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Food)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Food.setStatusBar(self.statusbar)
        self.menu_add = QtGui.QAction(Food)
        self.menu_add.setObjectName(_fromUtf8("menu_add"))
        self.menu_edit = QtGui.QAction(Food)
        self.menu_edit.setObjectName(_fromUtf8("menu_edit"))
        self.menu_create = QtGui.QAction(Food)
        self.menu_create.setObjectName(_fromUtf8("menu_create"))
        self.menu_dbcp = QtGui.QAction(Food)
        self.menu_dbcp.setObjectName(_fromUtf8("menu_dbcp"))
        self.menu_exit = QtGui.QAction(Food)
        self.menu_exit.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.menu_exit.setMenuRole(QtGui.QAction.QuitRole)
        self.menu_exit.setPriority(QtGui.QAction.HighPriority)
        self.menu_exit.setObjectName(_fromUtf8("menu_exit"))
        self.menu_about = QtGui.QAction(Food)
        self.menu_about.setObjectName(_fromUtf8("menu_about"))
        self.menu_dbsel = QtGui.QAction(Food)
        self.menu_dbsel.setObjectName(_fromUtf8("menu_dbsel"))
        self.menu_search = QtGui.QAction(Food)
        self.menu_search.setObjectName(_fromUtf8("menu_search"))
        self.menu_lang = QtGui.QAction(Food)
        self.menu_lang.setObjectName(_fromUtf8("menu_lang"))
        self.menu_help = QtGui.QAction(Food)
        self.menu_help.setObjectName(_fromUtf8("menu_help"))
        self.menu.addAction(self.menu_search)
        self.menu.addAction(self.menu_add)
        self.menu.addAction(self.menu_edit)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_create)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_exit)
        self.menu_2.addAction(self.menu_help)
        self.menu_2.addAction(self.menu_about)
        self.menu_3.addAction(self.menu_dbsel)
        self.menu_3.addAction(self.menu_dbcp)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.menu_lang)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(Food)
        QtCore.QObject.connect(self.menu_exit, QtCore.SIGNAL(_fromUtf8("triggered()")), Food.close)
        QtCore.QMetaObject.connectSlotsByName(Food)

    def retranslateUi(self, Food):
        Food.setWindowTitle(_translate("Food", "Food", None))
        self.mass_lab.setText(_translate("Food", "Масса, г", None))
        self.lip_lab.setText(_translate("Food", "Жиры", None))
        self.lip_sec_lab.setText(_translate("Food", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.ccal_lab.setText(_translate("Food", "Калорийность, ккал", None))
        self.ccal_sec_lab.setText(_translate("Food", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.carb_lab.setText(_translate("Food", "Углеводы", None))
        self.carb_sec_lab.setText(_translate("Food", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.searchbut.setText(_translate("Food", "Окно поиска", None))
        self.substitutebut.setText(_translate("Food", "Подставить", None))
        self.calcbut.setText(_translate("Food", "Посчитать", None))
        self.prot_lab.setText(_translate("Food", "Белки", None))
        self.prot_sec_lab.setText(_translate("Food", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.glyc_lab.setText(_translate("Food", "Гликемический индекс", None))
        self.glyc_sec_lab.setText(_translate("Food", "<html><head/><body><p align=\"right\"><br/></p></body></html>", None))
        self.menu.setTitle(_translate("Food", "&Меню", None))
        self.menu_2.setTitle(_translate("Food", "&Справка", None))
        self.menu_3.setTitle(_translate("Food", "&Настройки", None))
        self.menu_add.setText(_translate("Food", "&Добавить продукт в базу данных", None))
        self.menu_add.setShortcut(_translate("Food", "Ctrl+N", None))
        self.menu_edit.setText(_translate("Food", "&Редактировать базу данных", None))
        self.menu_edit.setShortcut(_translate("Food", "Ctrl+W", None))
        self.menu_create.setText(_translate("Food", "&Создать меню", None))
        self.menu_create.setShortcut(_translate("Food", "Ctrl+M", None))
        self.menu_dbcp.setText(_translate("Food", "С&копировать базу данных", None))
        self.menu_exit.setText(_translate("Food", "&Выход", None))
        self.menu_exit.setShortcut(_translate("Food", "Ctrl+Q", None))
        self.menu_about.setText(_translate("Food", "&О программе", None))
        self.menu_dbsel.setText(_translate("Food", "Выбрать &базу данных", None))
        self.menu_search.setText(_translate("Food", "&Искать продукт в базе данных", None))
        self.menu_search.setShortcut(_translate("Food", "Ctrl+S", None))
        self.menu_lang.setText(_translate("Food", "Выбрать &язык", None))
        self.menu_help.setText(_translate("Food", "&Помощь", None))
        self.menu_help.setShortcut(_translate("Food", "F1", None))

